name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
    - name: Build and deploy
      uses: appleboy/ssh-action@master
      env:
        CONTAINER: my-personal-portfolio-front
        IMAGE: my-personal-portfolio-front
        PROJECTDIR: my-personal-portfolio-vue
        PORT: 8081
        REPO: git@github.com:pedro1191/my-personal-portfolio-vue.git
        TAG: latest
        WORKDIR: portfolio/vue_projects
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: CONTAINER, IMAGE, PROJECTDIR, PORT, REPO, TAG, WORKDIR
        script: |
          rm -rf $WORKDIR/$PROJECTDIR
          mkdir -p $WORKDIR
          cd $WORKDIR
          git clone $REPO
          cd $PROJECTDIR
          docker stop $CONTAINER || true
          docker rm $CONTAINER || true
          docker rmi $IMAGE:$TAG || true
          docker build -t $IMAGE:$TAG .
          docker run -d --restart always --name $CONTAINER -p $PORT:80 $IMAGE:$TAG
          docker system prune -f
