name: Deployment Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
    - name: Build and deploy
      uses: appleboy/ssh-action@master
      env:
        CONTAINER: my-personal-portfolio-front
        ENV_FILE: ${{ secrets.ENV_FILE }}
        IMAGE: my-personal-portfolio-front
        TAG: latest
        WORKDIR: portfolio/vue_projects/my-personal-portfolio-vue
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: CONTAINER, ENV_FILE, IMAGE, TAG, WORKDIR
        script: |
          cd $WORKDIR
          git pull
          echo $ENV_FILE | base64 -d > .env
          source .env
          docker build -t $IMAGE:$TAG .
          docker stop $CONTAINER
          docker rm $CONTAINER
          docker run -d --name $CONTAINER -p $PORT:80 $IMAGE:$TAG
          docker system prune -f